baseURL = "https://ljnelson.github.io/"

title = "Blame Laird"

# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

publishDir = 'docs'

disqusShortname = ""
googleAnalytics = "G-VPDL2GWEZY"

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

# Missing translations will default to this content language
defaultContentLanguage = "en"

[markup.highlight]
lineNos = true
lineNumbersInTable = true
style = 'friendly'
tabWidth = 2

pluralizelisttitles = false

[params.info]
description = "Sum Ergo Mea Culpa Est"
title404 = "Nothing's here!"

[params.assets]
favicon = '/images/dougflag.svg' # "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Laird Nelson"
startYear = "2021"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006-01-02"
listDateFormat = "2006-01-02"
archiveDateFormat = "January 2"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#001dc0"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about", "search", "taxonomy_cloud"] # ["about","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
#codepen = "MunifTanjim"
#email = "contact@example.com"
#facebook = "MunifTanjim"
github = "ljnelson"
#gitlab = "MunifTanjim"
#instagram = "MunifTanjim"
linkedin = "ljnelson"
#twitter = "MunifTanjim"
#telegram = "MunifTanjim"
#google_scholar = "qc6CJjYAAAAJ"
#youtube = "UCT-U0rNerYxItGcuoPX-WYA"

[params.comments]
enable = false

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[params.comments.staticman]
enable = false
apiEndpoint = "https://api.staticman.net/v2/entry"
maxDepth = 2
username = "MunifTanjim"
repository = "minimo"

# Utterances: https://utteranc.es
[params.comments.utterances]
enable = false
issueTerm = "pathname" # pathname / url / title / og:title / <string>
label = ""
theme = "github-light"

[params.comments.utterances.github]
username = "ljnelson"
repository = "ljnelson.github.io"

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "About"
weight = -2
identifier = "about"
url = "https://about.me/lairdnelson"

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
